"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](pink)\
[angel](bg:pink fg:base)\
[](bg:base fg:pink)\
$directory\
[](fg:base bg:pink)\
$git_branch\
$git_status\
[](fg:pink bg:mauve)\
[$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python](fg:base bg:mauve)\
[](fg:mauve bg:teal)\
$docker_context\
$conda\
[](fg:teal bg:base)\
$time\
[ ](fg:base)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true
style = "bg:pink fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "fg:teal bg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:base bg:pink)'

[git_status]
format = '[($all_status$ahead_behind )](fg:base bg:pink)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[c]
symbol = " "
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[rust]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[golang]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[php]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[java]
symbol = " "
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[kotlin]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[haskell]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[python]
symbol = ""
format = '[ $symbol( $version) ](fg:base bg:mauve)'

[docker_context]
symbol = ""
format = '[ $symbol( $context) ](fg:base bg:mauve)'

[conda]
format = '[ $symbol( $environment) ](fg:base bg:mauve)'

[time]
disabled = false
time_format = "%I:%M %p"
format = '[  $time ](fg:pink bg:base)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[|>](bold fg:pink)'
error_symbol = '[|>](bold fg:red)'
