[[themes]]
name = "catppuccin_mocha"
[themes.palette]
# background = "#1e1e2e"
foreground = "#cdd6f4"
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"
bright_black = "#a6adc8"
bright_red = "#f37799"
bright_green = "#89d88b"
bright_yellow = "#ebd391"
bright_blue = "#74a8fc"
bright_magenta = "#f2aede"
bright_cyan = "#6bd7ca"
bright_white = "#f5e0dc"
